project:
  resources: ["images"]
  type: website
  output-dir: docs

website:
  title: "Aj Averett"
  favicon: favicon.png
  
  description: "Senior Consultant at Booz Allen & Adjunct Faculty at MTECH"
  site-url: "https://ajaverett.com" 
  open-graph: true
  twitter-card: true

  navbar:
    background: "#0f172a"
    foreground: light
    pinned: true
    collapse: true

    left:
      - text: "Home"
        href: index.qmd
      - href: "about.qmd"
        text: About
      - href: "map.qmd"
        text: Adventures

    # RIGHT SIDE: Icons & Search
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ajaverett
        aria-label: "LinkedIn"
      - icon: envelope
        href: mailto:ajaverett0+site@gmail.com
        aria-label: "Email"

format:
  html:
    theme: cosmo
    css: styles.css
